version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - 8000:8000
    environment:
      - DB_URL=postgresql://postgres:postgres@database:5432/Margins
    depends_on:
      database:
        condition: service_healthy


  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Margins
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 15

volumes:
  data: ~
  db:
    driver: local