version: '3.8'

services:
  app:
    build:
      context: .
      target: test
    ports:
      - 8000:8000
    env_file:
      - .env.test
    environment:
      - DB_URL=postgresql://postgres:postgres@database-test:5432/MarginsTest
    depends_on:
      database-test:
        condition: service_healthy


  database-test:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MarginsTest
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 15

